# Generated by Codex on 2026-04-28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_admin_users_staff(apps, schema_editor):
    User = apps.get_model("soc", "User")
    User.objects.filter(role="ADMIN").update(is_staff=True)


class Migration(migrations.Migration):

    dependencies = [
        ("soc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="type",
            field=models.CharField(
                choices=[
                    ("Network", "Network"),
                    ("Application", "Application"),
                    ("Database", "Database"),
                    ("Server", "Server"),
                    ("Endpoint", "Endpoint"),
                    ("IoT", "IoT"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="system",
            name="ip_address",
            field=models.GenericIPAddressField(
                protocol="IPv4",
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^(?:(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)\\.){3}(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)$",
                        message="Enter a valid IPv4 address.",
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action_type", models.CharField(max_length=100)),
                ("target_identifier", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RunPython(set_admin_users_staff, migrations.RunPython.noop),
    ]
