# Generated by Copilot on 2026-04-29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soc", "0002_auditlog_extend_system_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="threatactor",
            name="status",
            field=models.CharField(
                choices=[("UNVERIFIED", "Unverified"), ("VERIFIED", "Verified")],
                default="UNVERIFIED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="threatactor",
            name="origin_country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="threatactor",
            name="tactics",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="threatactor",
            name="threat_level",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High"), ("Critical", "Critical")],
                default="Low",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="threatactor",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
